# Generated by Django 4.2.6 on 2023-10-30 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, choices=[('1', '11'), ('2', '12'), ('3', '14'), ('4', '15'), ('5', '16'), ('6', '17'), ('7', '17.5'), ('8', '18'), ('9', '18.5'), ('10', '19'), ('11', '20')], default=0, max_length=50, verbose_name='開始時間')),
                ('end_time', models.CharField(blank=True, choices=[('1', '15'), ('2', '17'), ('3', '20'), ('4', '21'), ('5', '22'), ('6', '23'), ('7', '24')], default=0, max_length=50, verbose_name='終了時間')),
                ('date', models.DateField(verbose_name='日付')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_schedule', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
