# Generated by Django 4.2.4 on 2023-08-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohb_items',
            name='items_type',
            field=models.CharField(blank=True, choices=[('1', '食パン'), ('2', 'クロワッサン'), ('3', 'リュスティック'), ('4', 'パイ'), ('5', 'タルティーヌ'), ('6', 'その他')], default=1, max_length=15, verbose_name='タイプ'),
        ),
    ]
