# Generated by Django 4.2.4 on 2023-08-30 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohb', '0002_ohb_items_items_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ohb_items',
            old_name='items_type',
            new_name='item_type',
        ),
    ]
