# Generated by Django 4.2.4 on 2023-08-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ohb', '0003_rename_items_type_ohb_items_item_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_create', models.IntegerField(default=0, verbose_name='作成数')),
                ('item_los', models.IntegerField(default=0, verbose_name='作成数')),
                ('date', models.DateField(verbose_name='日付')),
            ],
        ),
        migrations.AlterField(
            model_name='ohb_items',
            name='item_name',
            field=models.CharField(max_length=50, verbose_name='商品名'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='items_counts',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ohb.ohb_items'),
        ),
    ]
