# Generated by Django 4.2.4 on 2023-08-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohb', '0004_items_counts_alter_ohb_items_item_name_delete_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_counts',
            name='item_los',
            field=models.IntegerField(default=0, verbose_name='ロス'),
        ),
    ]
