# Generated by Django 4.2.4 on 2023-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohb', '0005_alter_items_counts_item_los'),
    ]

    operations = [
        migrations.AddField(
            model_name='ohb_items',
            name='item_no',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
